sudo: true
language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

addons:
  apt:
    packages:
      - libudev-dev
      - libasound2-dev

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      wget http://libsdl.org/release/SDL2-2.0.5.tar.gz
      && tar -xzvf SDL2-2.0.5.tar.gz
      && pushd SDL2-2.0.5 && ./configure --prefix=/usr && make && sudo make install && popd;
    fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update
      && brew install sdl2;
    fi

before_script:
  - rustup toolchain install nightly
  - rustup component add --toolchain nightly rustfmt-preview
  - which rustfmt || cargo install --force rustfmt-nightly

script:
  - cargo +nightly fmt --all -- --write-mode=diff
  - cargo build
  - cargo test
