sudo: true
language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

addons:
  apt:
    packages:
      - libudev-dev
      - libasound2-dev

install:
  - rustup component add rustfmt
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      wget http://libsdl.org/release/SDL2-2.0.5.tar.gz
        && tar -xzvf SDL2-2.0.5.tar.gz
        && pushd SDL2-2.0.5 && ./configure --prefix=/usr && make && sudo make install && popd;
    fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update && brew install sdl2;
    fi

script:
  - cargo fmt -- --check
  - cargo build
  - cargo test
